"""Compact file-first layout for the desktop application."""
from pathlib import Path
import queue
import sys
import customtkinter as ctk


def build_main_ui(app, redirect_text):
    app.title("Whisper Studio")
    app.protocol("WM_DELETE_WINDOW", app.on_close)
    app.geometry("1000x820")
    app.minsize(860, 720)
    base = Path(__file__).resolve().parent.parent
    app.input_dir, app.output_dir = base / "input", base / "output"
    app.ui_events = queue.Queue()
    app.grid_columnconfigure(0, weight=1)
    app.grid_rowconfigure(1, weight=1)
    app.configure(fg_color="#111820")

    header = ctk.CTkFrame(app, fg_color="transparent")
    header.grid(row=0, column=0, sticky="ew", padx=24, pady=(18, 12))
    ctk.CTkLabel(header, text="Whisper Studio", font=ctk.CTkFont(size=25, weight="bold")).pack(anchor="w")
    ctk.CTkLabel(header, text="De audio a texto, con cada hablante identificado.", text_color="#9DAFBE").pack(anchor="w")

    files = ctk.CTkFrame(app, fg_color="#1C2732", corner_radius=12)
    files.grid(row=1, column=0, sticky="nsew", padx=24, pady=(0, 12))
    files.grid_columnconfigure(0, weight=1)
    files.grid_rowconfigure(1, weight=1)
    toolbar = ctk.CTkFrame(files, fg_color="transparent")
    toolbar.grid(row=0, column=0, sticky="ew", padx=14, pady=12)
    app.lbl_file_count = ctk.CTkLabel(toolbar, text="Audios", font=ctk.CTkFont(size=16, weight="bold"))
    app.lbl_file_count.pack(side="left")
    ctk.CTkButton(toolbar, text="Añadir audios…", width=145, command=app.add_audio_files).pack(side="right", padx=(8, 0))
    ctk.CTkButton(toolbar, text="Añadir carpeta…", width=135, fg_color="#344453", command=app.browse_input).pack(side="right", padx=8)
    ctk.CTkButton(toolbar, text="Vaciar lista", width=90, fg_color="transparent", border_width=1, command=app.clear_audio_files).pack(side="right")
    app.scrollable_file_list = ctk.CTkScrollableFrame(files, height=150, fg_color="transparent")
    app.scrollable_file_list.grid(row=1, column=0, sticky="nsew", padx=10, pady=(0, 10))
    app.file_checkboxes = []
    app.clear_audio_files()
    # Internal folder value retained for folder browsing; paths are not the primary input.
    app.entry_input = ctk.CTkEntry(app)
    app.entry_input.insert(0, str(app.input_dir))

    settings = ctk.CTkFrame(app, fg_color="#1C2732", corner_radius=12)
    settings.grid(row=2, column=0, sticky="ew", padx=24, pady=(0, 12))
    first = ctk.CTkFrame(settings, fg_color="transparent")
    first.pack(fill="x", padx=14, pady=(12, 4))
    ctk.CTkLabel(first, text="Modelo").pack(side="left", padx=(0, 8))
    app.option_model = ctk.CTkOptionMenu(first, values=["medium", "turbo", "small", "base", "tiny", "large-v3"], width=115)
    app.option_model.pack(side="left")
    ctk.CTkLabel(first, text="Idioma").pack(side="left", padx=(18, 8))
    app.option_language = ctk.CTkOptionMenu(first, values=["Spanish", "English", "Portuguese", "French", "Italian", "German", "Japanese"], width=115)
    app.option_language.pack(side="left")
    ctk.CTkLabel(first, text="Hablantes").pack(side="left", padx=(18, 8))
    app.entry_speakers = ctk.CTkEntry(first, width=95, placeholder_text="Automático")
    app.entry_speakers.pack(side="left")
    ctk.CTkButton(first, text="Perfil portátil", width=125, command=app.apply_gpu_profile).pack(side="right", padx=(10, 0))

    second = ctk.CTkFrame(settings, fg_color="transparent")
    second.pack(fill="x", padx=14, pady=8)
    app.check_reuse = ctk.CTkCheckBox(second, text="Reutilizar texto guardado", width=205)
    app.check_reuse.pack(side="left")
    app.check_safe_mode = ctk.CTkCheckBox(second, text="Diarización en CPU", width=185)
    app.check_safe_mode.pack(side="left", padx=12)
    app.check_safe_mode.deselect()
    app.check_cpu = ctk.CTkCheckBox(second, text="Whisper en CPU", width=155)
    app.check_cpu.pack(side="left")
    app.check_debug = ctk.CTkCheckBox(second, text="Monitor GPU", width=120)
    app.option_gpu_profile = ctk.CTkOptionMenu(second, values=["GPU rápida", "GPU compatible"], width=145)
    app.option_gpu_profile.pack(side="right", padx=(12, 0))

    credentials = ctk.CTkFrame(settings, fg_color="transparent")
    credentials.pack(fill="x", padx=14, pady=(0, 12))
    ctk.CTkLabel(credentials, text="Token Hugging Face", text_color="#9DAFBE").pack(side="left", padx=(0, 12))
    app.entry_token = ctk.CTkEntry(credentials, show="*", width=220, placeholder_text="Necesario para identificar hablantes")
    app.entry_token.pack(side="left")
    ctk.CTkLabel(credentials, text="Procesamiento local · audio en tu equipo", text_color="#9DAFBE").pack(side="right")

    destination = ctk.CTkFrame(app, fg_color="transparent")
    destination.grid(row=3, column=0, sticky="ew", padx=24, pady=(0, 12))
    destination.grid_columnconfigure(1, weight=1)
    ctk.CTkLabel(destination, text="Guardar en", text_color="#9DAFBE").grid(row=0, column=0, padx=(0, 10))
    app.entry_output = ctk.CTkEntry(destination)
    app.entry_output.insert(0, str(app.output_dir))
    app.entry_output.grid(row=0, column=1, sticky="ew")
    ctk.CTkButton(destination, text="Cambiar…", width=85, fg_color="#344453", command=app.browse_output).grid(row=0, column=2, padx=8)
    ctk.CTkButton(destination, text="Ver resultados", width=115, fg_color="#344453", command=app.open_output_folder).grid(row=0, column=3)
    app.load_config()
    app.bind("<Control-o>", lambda event: app.add_audio_files())

    actions = ctk.CTkFrame(app, fg_color="transparent")
    actions.grid(row=4, column=0, sticky="ew", padx=24, pady=(0, 8))
    actions.grid_columnconfigure(0, weight=1)
    app.btn_start = ctk.CTkButton(actions, text="Transcribir e identificar hablantes", height=44, font=ctk.CTkFont(size=15, weight="bold"), command=app.start_thread)
    app.btn_start.grid(row=0, column=0, sticky="ew", padx=(0, 12))
    app.btn_open_editor = ctk.CTkButton(actions, text="Abrir transcripción…", width=190, height=44, fg_color="#344453", command=app.open_editor_dialog)
    app.btn_cancel = ctk.CTkButton(actions, text="Cancelar", width=85, height=44, state="disabled", fg_color="#803C3C", command=app.cancel_process)
    app.btn_cancel.grid(row=0, column=1, padx=(0, 12))
    app.btn_open_editor.grid(row=0, column=2)
    app.label_status = ctk.CTkLabel(app, text="Añade uno o varios audios para empezar.", text_color="#9DAFBE", anchor="w", wraplength=840)
    app.label_status.grid(row=5, column=0, sticky="ew", padx=24, pady=(0, 4))
    app.textbox_log = ctk.CTkTextbox(app, state="disabled", height=95, font=("Consolas", 11))
    app.textbox_log.grid(row=6, column=0, sticky="ew", padx=24, pady=(0, 16))
    sys.stdout = redirect_text(app.textbox_log, sys.__stdout__, event_queue=app.ui_events)
    sys.stderr = redirect_text(app.textbox_log, sys.__stderr__, event_queue=app.ui_events)
    app.after(60, app.drain_ui_events)
